fix: implement retry logic for fetching Pokémon data

diff --git a/Advanced_shell/batchProcessing-0x02 b/Advanced_shell/batchProcessing-0x02
--- a/Advanced_shell/batchProcessing-0x02
+++ b/Advanced_shell/batchProcessing-0x02
@@ -5,11 +5,29 @@
 
 POKEMONS=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
 OUTPUT_FILE="${poke}.json"
+MAX_RETRIES=3
 
 for poke in "${POKEMONS[@]}";
 do
-    echo "Fetching data for $poke..."
-    curl -s -o  "$OUTPUT_FILE" -X GET "https://pokeapi.co/api/v2/pokemon/$poke"
-    echo "saved data $to OUTPUT_FILE"
+    success=false
+    for ((i-1; i<=MAX_RETRIES; i++));
+    do
+        echo "Fetching data for $poke..."
+        curl -s -o  "$OUTPUT_FILE" -X GET "https://pokeapi.co/api/v2/pokemon/$poke"
+        
+        if [ $? -eq 0 ]; then
+            success=true
+            echo "saved data for $poke to OUTPUT_FILE"
+            break
+        else
+            echo "Attempt $i/$MAX_RETRIES for $poke failed. Retrying..."
+            sleep 3
+        fi
+    done
+    if ! $success; then 
+        echo "All attempts to get $poke data failed"
+    fi
     sleep 3
 done
+
+## i could also do it in a countdown way like for failed attpemts reduce the number
